# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ericswpark
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Seoul
          repositories_skipped: android_kernel_samsung_msm8974, android_device_samsung_frescolteskt, SM-N750S_KOR_LL_Opensource, SCH-I909_CHN_GB_Opensource_Update1
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 0%
